### -------------------------- MENUS

### Doit récupérer les menus, repas, recettes, ingredients de la semaine du Lun 2023-04-10 au Dim 2023-04-16
GET http://127.0.0.1:3000/api/menus/2023-04-15

### Créer un repas pour le menu d'id 15
POST http://127.0.0.1:3000/api/menus/15/repas
Content-Type: application/json

{
    "nb_convives": 8
}



### -------------------------- REPAS

### Met à jour le nombre de convives d'un repas et/ou la recette d'un repas (ajoute la recette si elle n'existe pas)
PUT http://127.0.0.1:3000/api/repas/3/recettes/3
Content-Type: application/json

{
    "nb_convives": 4,
    "recettes": [
        {
            "id": 3
        },
        {
            "id": 5
        }
    ]

}

### TODO: Modifier le repas d'id 8
PUT http://127.0.0.1:3000/api/repas/8
Content-Type: application/json

{
    "nb_convives": 13
}

### Supprimer le repas par son id
DELETE http://127.0.0.1:3000/api/repas/12

### Supprimer pour le repas avec repasId la recette recetteId
DELETE http://127.0.0.1:3000/api/repas/3/recettes/3


### -------------------------- RECETTES

### Récupérer toutes les recettes
GET http://127.0.0.1:3000/api/recettes

### Créer une recette sans ingrédients et retourner le résultat
POST http://127.0.0.1:3000/api/recettes
Content-Type: application/json

{
    "nom": "Recette de Test",
    "nb_personnes": 12,
    "etapes": "1. bla, 2. blabla, 3. blablabla"
}

### Créer une recette avec ingrédients et retourner le résultat
POST http://127.0.0.1:3000/api/recettes
Content-Type: application/json

{
    "nom": "Carrotes aux Oignons",
    "nb_personnes": 3,
    "etapes": "1. bla, 2. blabla, 3. blablabla",
    "ingredients": [
        {
            "id": 8,
            "nom": "carotte",
            "utiliser": {
                "quantite": "10.00",
                "unite": "unité(s)"
            }
        },
        {
            "id": 3,
            "nom": "oignon",
            "utiliser": {
                "quantite": "5.00",
                "unite": "unité(s)"
            }
        }
    ]
}

### Modifier la recette d'id 6 et retourner le résultat
PUT http://127.0.0.1:3000/api/recettes/8
Content-Type: application/json

{
    "nom": "Recette de Test",
    "nb_personnes": 33,
    "etapes": "1. bla. 2. blabla. 3. blablabla"
}

### Modifier la recette d'id 6 et retourner le résultat
PUT http://127.0.0.1:3000/api/recettes/6
Content-Type: application/json

{
    "nom": "Carrotes aux Oignons",
    "nb_personnes": 3,
    "etapes": "1. bla, 2. blabla, 3. blablabla",
    "ingredients": [
        {
            "id": 8,
            "nom": "carottes",
            "utiliser": {
                "quantite": "18.00",
                "unite": "unité(s)"
            }
        },
        {
            "id": 3,
            "nom": "oignon",
            "utiliser": {
                "quantite": "13.00",
                "unite": "unité(s)"
            }
        }
    ]
}

### Supprimer la recette d'id 6
DELETE http://127.0.0.1:3000/api/recettes/6

### Supprimer de la recette d'id 6 l'ingredient d'id 2
DELETE http://127.0.0.1:3000/api/recettes/6/ingredients/3



### -------------------------- INGREDIENTS

### Récupérer toutes les ingredients
GET http://127.0.0.1:3000/api/ingredients

### Créer une ingredient et retourner le résultat
POST http://127.0.0.1:3000/api/ingredients
Content-Type: application/json

{
    "nom": "Ingredient de Test"
}

### Modifier l'ingredient d'id 21 et retourner le résultat
PUT http://127.0.0.1:3000/api/ingredients/21
Content-Type: application/json

{
    "nom": "Recette de Test PUT"
}

### Supprimer l'ingredient d'id 21
DELETE http://127.0.0.1:3000/api/ingredients/21


### -------------------------- STATISTIQUES
###
GET http://127.0.0.1:3000/api/menus/2023-04-15/ingredients/percents

### Récupère tous les ingrédients et leur quantité pour 1 mois
GET http://127.0.0.1:3000/api/menus/2023-04-15/ingredients

### Le nombre de chaque recette dans le mois
GET http://127.0.0.1:3000/api/menus/2023-04-15/recettes
