### Doit récupérer les menus, repas, recettes, ingredients de la semaine du Lun 2023-04-10 au Dim 2023-04-16
GET http://127.0.0.1:3000/api/menus/2023-04-15

### Doit récupérer les mêmes menus, repas, recettes, ingredients que la requête précedente
GET http://127.0.0.1:3000/api/menus/2023-04-10

### Créer un repas pour le menu d'id 2
POST http://127.0.0.1:3000/api/menus/2/repas
Content-Type: application/json

{
    "nb_convives": 8
}
