### Doit récupérer les menus, repas, recettes, ingredients de la semaine du Lun 2023-04-10 au Dim 2023-04-16
GET http://127.0.0.1:3000/api/menus/2023-04-15

### Doit récupérer les mêmes menus, repas, recettes, ingredients que la requête précedente
GET http://127.0.0.1:3000/api/menus/2023-04-10

### Créer un repas pour le menu d'id 2
POST http://127.0.0.1:3000/api/menus/15/repas
Content-Type: application/json

{
    "nb_convives": 8
}

### TODO: Modifier le repas d'id 8
POST http://127.0.0.1:3000/api/repas/8
Content-Type: application/json

{
    "nb_convives": 13
}

### Supprimer le repas d'id 12
DELETE http://127.0.0.1:3000/api/repas/12



### -------------------------- RECETTES

### Récupérer toutes les recettes
GET http://127.0.0.1:3000/api/recettes

### Créer une recette et retourner le résultat
POST http://127.0.0.1:3000/api/recettes
Content-Type: application/json

{
    "nom": "Recette de Test",
    "nb_personnes": 12,
    "etapes": "1. bla, 2. blabla, 3. blablabla"
}

### Modifier la recette d'id 6 et retourner le résultat
PUT http://127.0.0.1:3000/api/recettes/6
Content-Type: application/json

{
    "nom": "Recette de Test",
    "nb_personnes": 6,
    "etapes": "1. bla. 2. blabla. 3. blablabla"
}

### Supprimer la recette d'id 6
DELETE http://127.0.0.1:3000/api/recettes/6



### -------------------------- INGREDIENTS

### Récupérer toutes les ingredients
GET http://127.0.0.1:3000/api/ingredients

### Créer une ingredient et retourner le résultat
POST http://127.0.0.1:3000/api/ingredients
Content-Type: application/json

{
    "nom": "Ingredient de Test"
}

### Modifier l'ingredient d'id 21 et retourner le résultat
PUT http://127.0.0.1:3000/api/ingredients/21
Content-Type: application/json

{
    "nom": "Recette de Test PUT"
}

### Supprimer l'ingredient d'id 21
DELETE http://127.0.0.1:3000/api/ingredients/21



